---
- name: Copy hostname.sh
  copy: src=files/hostname.sh dest=/usr/local/bin/hostname.sh owner=root group=root mode=0755

- name: Installing curl
  apt: name="{{ item }}" update_cache=yes
  with_items:
  - curl
  - ca-cacert
   
- name: Execute Hostname
  shell: /usr/local/bin/hostname.sh
