---
- name: Copy hostname.sh
  copy: src=files/hostname.sh dest=/usr/local/bin/hostname.sh owner=root group=root mode=0755

- name: Installing curl
  apt: name="{{ item }}" update_cache=yes
  with_items:
  - curl
  - ca-cacert
  
- name: Generating Hostname
  command: /usr/local/bin/hostname.sh
  register: g_name

- name: Setting Hostname
  hostname: name="{{ g_name.stdout }}.ws.chaosnetz.org"

- name: Mapping Hostname to 127.0.0.1
  blockinfile:
    marker: "# {mark} ANSIBLE GENERATED HOSTNAME"
    dest: /etc/hosts
    block: |
      127.0.0.1 {{ g_name.stdout }} {{ g_name.stdout }}.ws.chaosnetz.org  
